name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements_pip.txt
        mkdir -p ./data_copy
        cp ./data/ProtocollChat2_15_5_24.txt ./data_copy/ProtocollChat2_15_5_24.txt
        cp ./data/activitys_12_3_24.txt ./data_copy/activitys_12_3_24.txt
        cp ./data/features.csv ./data_copy/features.csv
        cp ./data/preprocessed_chat.csv ./data_copy/preprocessed_chat.csv
        cp ./data/scores_10_3_24_.txt ./data_copy/scores_10_3_24_.txt

    - name: Run feature extraction tests
      run: python scripts/test_feature_extraction.py

    - name: Run model building tests
      run: python scripts/test_model_building.py
