name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up job
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_pip.txt

      - name: Ensure data directory
        run: mkdir -p ./data

      - name: Copy data files
        run: |
          cp ./data/ProtocollChat2_15_5_24.txt ./data_copy/ProtocollChat2_15_5_24.txt
          cp ./data/activitys_12_3_24.txt ./data_copy/activitys_12_3_24.txt
          cp ./data/features.csv ./data_copy/features.csv
          cp ./data/preprocessed_chat.csv ./data_copy/preprocessed_chat.csv
          cp ./data/scores_10_3_24_.txt ./data_copy/scores_10_3_24_.txt

      - name: Run feature extraction tests
        run: python scripts/test_feature_extraction.py

      - name: Run model building tests
        run: python scripts/test_model_building.py

      - name: Generate documentation
        run: codeium generate-docs

      - name: Update README
        run: python scripts/update_readme.py
