name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Install Sphinx
      run: |
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build documentation
      run: |
        sphinx-build -b html docs/source docs/build

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      env:
        CLASSICAL_PAT: ${{ secrets.CLASSICAL_PAT }}
      run: |
        git add docs/build
        git commit -m "Automated update of documentation"
        git push https://GoMightyAlgorythmGo:${{ secrets.CLASSICAL_PAT }}@github.com/GoMightyAlgorythmGo/OMG_PGFM.git
